name: build and publish

on: push

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      # the url replacement here is both to provide the key and to get around an npm bug where all git dependencies use
      # ssh even when you specify https
      - name: Build ui
        run: |
          git config --global url."https://x-token-auth:${{ secrets.DYN_LAYOUT_REPO_KEY }}@bitbucket.org/aglabs/".insteadOf ssh://git@bitbucket.org/aglabs/
          make preview-ui

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 30
